if (APPLE)
    FIND_LIBRARY(SENSEL_LIBRARY Sensel
        PATHS /usr/local/lib
        NO_DEFAULT_PATH
    )
    SET(SENSEL_LIBRARIES ${SENSEL_LIBRARY})
    FIND_PATH(SENSEL_INCLUDE_DIR sensel.h
        PATHS /usr/local/include
        NO_DEFAULT_PATH
    )
    SET(SENSEL_INCLUDE_DIRS ${SENSEL_INCLUDE_DIR})
elseif("${CMAKE_SYSTEM}" MATCHES "Linux")
    FIND_LIBRARY(SENSEL_LIBRARY Sensel
        PATHS /usr/lib
        NO_DEFAULT_PATH
    )
    SET(SENSEL_LIBRARIES ${SENSEL_LIBRARY})
    FIND_PATH(SENSEL_INCLUDE_DIR sensel.h
        PATHS /usr/include
        NO_DEFAULT_PATH
    )
    SET(SENSEL_INCLUDE_DIRS ${SENSEL_INCLUDE_DIR})
endif()

